version: "3.9"
services:
  shorty:
    container_name: shorty-app
    build: ./
    command: ./shorty
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    container_name: ${REDIS_HOST}
    image: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local
