name: lint

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  tests:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install golangci
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.50.1

      - name: Lint
        run: make lint
